title: Kurt Unger
logo: images/kurt.jpg
description: 2023 IT graduate focused on software development and digital media
#show_downloads: true
url: 'https://kurtu0.github.io/' 
baseurl: ''
theme: jekyll-theme-minimal
