title: Kurt Unger
logo: images/kurt.jpg
description: Software and Digital Media Specialist
#show_downloads: true
url: 'https://kurtu0.github.io/' 
baseurl: ''
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
